"""Add index to Post.date_created

Revision ID: 028f72e3e1dd
Revises: 
Create Date: 2025-10-05 04:13:07.789485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028f72e3e1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_date_created'), ['date_created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_date_created'))

    # ### end Alembic commands ###
